# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Sharelock"
client_id = "17d4cb5eec7ab069f8a96c270cbe4a62"
application_url = "https://appeal-sr-against-workout.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://appeal-sr-against-workout.trycloudflare.com/auth/callback",
  "https://appeal-sr-against-workout.trycloudflare.com/auth/shopify/callback",
  "https://appeal-sr-against-workout.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "cbd-11.myshopify.com"
